pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps { git 'https://github.com/saifjm54/jee-enterprise-app.git'}
        }
        stage('Build') {
            steps { sh 'mvn clean package' }
        }
        stage('Test') {
            steps { sh 'mvn test'}
        }
        stage('Docker Build') {
            steps { sh 'docker build -t myapp:latest .'}
        }
        stage('Deploy to Kubernetes') {
            steps { sh 'kubectl apply -f kubernetes/deployment.yaml'}
        }
    }
}